apiVersion: v1
kind: Secret
metadata:
  name: my-secret
type: Opaque
data:
  CONNECTION_STRING: bW9uZ29kYitzcnY6Ly9zY2hvb2wxOkFrNlVEenY4YnpZNDB5ZE5AY2x1c3RlcjAucXpubm9zaS5tb25nb2RiLm5ldC8/cmV0cnlXcml0ZXM9dHJ1ZSZ3PW1ham9yaXR5JmFwcE5hbWU9Q2x1c3RlcjA=
  JWT_KEY: WW91clZlcnlTZWNyZXRLZXlXaXRoRW5vdWdoTGVuZ3RoMTIzNDU=
